#
name: Main
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    uses: ./.github/workflows/isofun--api-ci.yml
  deploy:
    needs: build
    uses: ./.github/workflows/isofun--api-cd.yml
  extra-test:
    needs: deploy
    uses: ./.github/workflows/dev/isofun-extra.yml

